remove test exit

diff --git a/CRYPT b/CRYPT
--- a/CRYPT
+++ b/CRYPT
@@ -24,13 +24,12 @@ for a in base doc lib32 kernel; do
 			echo "try mounting as tmpfs: mount -o size=300M -t tmpfs tmpfs $bsd"
 			exit 1
 		fi
-		echo "Can't find FreeBSD installation file $a in $bsd" >&2
+		echo "Can't find FreeBSD installation file $a.txz in $bsd" >&2
 		echo "trying to download it"
 		fetch -o $bsd/$a.txz ftp://ftp.freebsd.org/pub/FreeBSD/releases/$(uname -m)/$(uname -r |sed 's/-.*/-RELEASE/')/$a.txz
 		quit=$?
 		set -x
 	fi
-	quit=1
 done
 if [ $quit -ne 0 ]; then
 	echo "Something went wrong, while downloading FreeBSD installation files"
